# -*- coding: utf-8 -*-
"""1.3.Pattern Match.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnCJB4unRWSPRkCDHe7-8Bgo9OIlFvgb
"""

def search(pat, txt):
    m = len(pat)
    n = len(txt)

    for i in range(n - m + 1):
        match = True
        for j in range(m):
            if txt[i + j] != pat[j]:
                match = False
                break
        if match:
            print(f"Pattern found at index {i}")

# Example usage
txt = "ABABDABACDABABCABAB"
pat = "ABABCABAB"
search(pat, txt)