# -*- coding: utf-8 -*-
"""3.1.Divide&conquer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NnmMTFpbbRssB2m2IxLHyowemicb8xP
"""

def find_max_min(arr, low, high):
    if low == high:  # Only one element
        return arr[low], arr[low]
    elif high == low + 1:  # Two elements
        if arr[low] > arr[high]:
            return arr[low], arr[high]
        else:
            return arr[high], arr[low]
    else:
        mid = (low + high) // 2
        max1, min1 = find_max_min(arr, low, mid)
        max2, min2 = find_max_min(arr, mid + 1, high)
        return max(max1, max2), min(min1, min2)

# Example usage
arr = [10, 20, 3, 45, 6, 78, 2, 56]
maximum, minimum = find_max_min(arr, 0, len(arr) - 1)
print("Maximum:", maximum)
print("Minimum:", minimum)